### ISSUE TITLE
Addressing Technical Debt, Bugs, Missing Features, Refactor

### ISSUE THREAD

**Issue by andricDu** [overture-stack/ego#188]
## Requirements before this is ready for ICGC Integration

Not ordered by priority

- [x] Fix silent exception supression in Token Service  (parent of https://github.com/overture-stack/ego/issues/187)
- [ ] Need better error handling for redundant scopes (parent of https://github.com/overture-stack/ego/issues/183)
- [ ] Have Ego use POJOs representing proper responses, both successful and error responses. (parent of https://github.com/overture-stack/ego/issues/189)
  - [ ] Prettier responses (parent of https://github.com/overture-stack/ego/issues/119)
- [x]  Investigate Hibernate/JPA usage and correctness.  (parent of https://github.com/overture-stack/ego/issues/190)
  - [x] Cleanup and Refactor of Hibernate/JPA implementation (parent of https://github.com/overture-stack/ego/issues/191)
  - [x] Cleanup and Refactor of Group Centric Code (parent of https://github.com/overture-stack/ego/issues/224)
- [x] Junit Integration Tests
  - [x] Base Integration Tests Template (parent of https://github.com/overture-stack/ego/issues/192)
  - [x] Group (parent of https://github.com/overture-stack/ego/issues/210)
- [x] Fix CRUD (parent of https://github.com/overture-stack/ego/issues/193)
- [x] Implement CSRF with JWT CSRF Tokens (parent of https://github.com/overture-stack/ego/issues/194)
- [x] Docker Compose should Apply Migrations (parent of https://github.com/overture-stack/ego/issues/169)
- [x] Audit Ego Codebase (parent of https://github.com/overture-stack/ego/issues/167)
- [x] Tokens should be issued by user id not user email  (parent of https://github.com/overture-stack/ego/issues/195)
- [x] Endpoint to list Tokens for a user (parent of https://github.com/overture-stack/ego/issues/196)
- [x] Endpoint to revoke/delete token (parent of https://github.com/overture-stack/ego/issues/197)
- [x] Not all applications should be able to manipulate access token (parent of https://github.com/overture-stack/ego/issues/198)
- [x] Document different models and their uses (parent of https://github.com/overture-stack/ego/issues/118)
- [ ] Integrate finished client secret encryption into codebase (parent of https://github.com/overture-stack/ego/issues/199)
- [x] Apply Code Formatter uniformly across all source (parent of https://github.com/overture-stack/ego/issues/200)
- [x] Removes current demo user implementation (parent of https://github.com/overture-stack/ego/issues/202)
  - [x] Demo user service for demo run profile (parent of https://github.com/overture-stack/ego/issues/205)
- [ ] Get methods on services return optionals (parent of https://github.com/overture-stack/ego/issues/203)
- [ ] Find methods in services should return collection (parent of https://github.com/overture-stack/ego/issues/204)
- [x] Endpoint to delete users (parent of https://github.com/overture-stack/ego/issues/207)
- [x] Decouple DTO from DAO (https://github.com/overture-stack/ego/issues/228)
  - [ ] Remove JsonViews from all entities (https://github.com/overture-stack/ego/issues/229)
- [x] Nonces for auth code flow (https://github.com/overture-stack/ego/issues/233)
- [ ] Do tokens still work if user/group/application are not approved? (https://github.com/overture-stack/ego/issues/260)

*This does not include required UI changes*
