### ISSUE TITLE
Demoable Ego

### ISSUE THREAD

**Issue by andricDu** [overture-stack/ego#19]
The goal of this is to have a publicly available instance of Ego with which any user can log into an play with. 

## Tasks

- [x] Allow users to log in and be assigned admin rights
- [x] Do not persist users logging in to Ego into the Users table (to preserve privacy of users interacting with the demo)
- [x] Make behavior mentioned above toggle-able from a config value inside the `application.yml`
- [x] Script to auto-populate database with dummy users
- [x] Cronjob that refreshes the user database nightly to clean database of changes from users

## Resources
[Ego Source Code](https://github.com/overture-stack/ego)
[Ego UI Source Code](https://github.com/kids-first/kf-drp-auth-ui)

**Comment by andricDu** [comment]
Let me know if you need any resources. At some point you might want an Amazon RDS instance for a demo postgres database.

**Comment by joneubank** [comment]
Above commit ads a Spring Profile to enable the demo features. Run the application with the demo profile active.

Add the following command line option when running the jar:
`-spring.profiles.active=prod`

Note: activating any profile removes the "default" profile, which will cause an error in our case. Ensure you also run the "default" or "auth" profile to avoid issues.

**Comment by joneubank** [comment]
Demo server running with nginx, https configured, and running the ego api locally with the demo and auth profile active.

https://demo.ego.kfdrc.org/swagger-ui.html

**Comment by joneubank** [comment]
Cronjob added to execute the user dummy-data script at midnight daily. 200 randomly generated users will be available in the DB.

Next Step (as discussed with @cheapsteak ): Create dummy-data for applications and groups, including user relations to each.

**Comment by joneubank** [comment]
Had to also make users "Approved" status before registration would work. Demo registered users will be approved by default and can now access the API's.

**Comment by joneubank** [comment]
A lot of this work got overwritten by the JPA refactoring. I am redoing it now.
